all:
	python solution.py < test.txt
	python solution.py < bigtest.txt
	# ruby solution.rb < test.txt
	# runhaskell solution.hs < test.txt
	# g++ -std=c++11 -g -Wall -Wextra -pedantic -o prog solution.cpp
	# ./prog < test.txt
	



